set $firefox_mode "1. WORK  2. UNIVERSITY  3. PERSONAL"
mode $firefox_mode {
    bindsym 1 exec --no-startup-id firefox -P "WORK" --no-remote, mode "default"
    bindsym 2 exec --no-startup-id firefox -P "UNIVERSITY" --no-remote, mode "default"
    bindsym 3 exec --no-startup-id firefox -P "PERSONAL" --no-remote, mode "default"
    bindsym Escape mode "default"
    bindsym Return mode "default"
}
